# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iOSExampleRiskCocoapods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Example Custom
  pod 'Risk', '3.0.3'
  # to debug locally switch this around and it'll use the local SDK version instead of the deployed version
  # pod 'Risk', :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
